name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Node CI
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
            path: node_modules
            key: ${{ runner.os }}-build-node_modules-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-build-node_modules-
              ${{ runner.os }}-build-
              ${{ runner.os }}-

      - name: Install dependencies, lint and build
        run: |
          yarn
          bin/lint
